[soto]
runner = "soto-fbx"

[prop]
name = "layl_debug/test_cubes" # TODO: Make use of prefix and relative path
type = "static" # TODO: Add implementation
surface_prop = "default" # TODO: Add implementation

[model]
reference = "test_cubes.fbx" # TODO: Add filters

[sequences.move]
file = "test_cubes_move.fbx"
params = "loop fps 30"
