[package]
name = "soto-fbx"
description = "Source Tooling FBX tool."
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
sotolib-fbx = {path = "../sotolib-fbx"}
sotolib-smd = {path = "../sotolib-smd"}
